version: "3.0"

services:
  deployer:
    build:
      context: ./import-map-deployer/
    ports:
      - 5000:5000
    volumes:
      - ./deployer-config.json:/www/config.json
      - ./import-map:/www/import-map

  root-config:
    build:
      context: ./root-config/
    ports:
      - "8080:9000"
    volumes:
      - ./root-config:/app
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true

  theseus:
    build:
      context: ./theseus/
    ports:
      - "8081:8080"
    volumes:
      - ./theseus:/app
    stdin_open: true
    environment:
      CHOKIDAR_USEPOLLING: true
